# ROCKCHIP Platform Support
snd-soc-rockchip-objs := rk28-pcm.o
snd-soc-rockchip-iis-objs := rk28-iis.o

obj-$(CONFIG_SND_ROCKCHIP_SOC) += snd-soc-rockchip.o
obj-$(CONFIG_SND_ROCKCHIP_SOC_IIS) += snd-soc-rockchip-iis.o

# ROCKCHIP Machine Support
snd-soc-wm8988-objs := rk28_wm8988.o
snd-soc-rk1000-objs := rk28_rk1000codec.o

obj-$(CONFIG_SND_ROCKCHIP_SOC_WM8988) += snd-soc-wm8988.o
obj-$(CONFIG_SND_ROCKCHIP_SOC_RK1000) += snd-soc-rk1000.o
