obj-$(CONFIG_LCD_NULL) += lcd_null.o
obj-$(CONFIG_TV_NULL) += tv_null.o
obj-$(CONFIG_HDMI_NULL) += hdmi_null.o


obj-$(CONFIG_LCD_TD043MGEA1) += lcd_td043mgea1.o
obj-$(CONFIG_LCD_HSD070IDW1) += lcd_hsd800x480.o
obj-$(CONFIG_LCD_HL070VM4AU) += lcd_hl070vm4.o
obj-$(CONFIG_LCD_LQ048Y3DH01) += lcd_LQ048Y3DH01.o
obj-$(CONFIG_LCD_KD50G2_40TM) += lcd_kd50g240tm.o
obj-$(CONFIG_LCD_BM999INCH89) += lcd_bm999inch89.o
ifeq ($(CONFIG_MACH_RK2808SDK),y)
obj-$(CONFIG_LCD_TJ048NC01CA) 		+= lcd_tj048nc01ca.o
endif
ifeq ($(CONFIG_MACH_PWS700AA),y)
obj-$(CONFIG_LCD_TJ048NC01CA) 		+= lcd_tj048nc01ca.o
endif
ifeq ($(CONFIG_MACH_LANMO_W7),y)
obj-$(CONFIG_LCD_TJ048NC01CA) 		+= lanmow7_lcd048.o
endif


obj-$(CONFIG_HDMI_ANX7150) += hdmi_anx7150.o
obj-$(CONFIG_TV_RK1000) += tv_rk1000.o


